---
name: main
run-name: Create Iplike builder OCI for CICD infrastructure
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
jobs:
  oci-builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Create Dockerfile
        run: make Dockerfile
      - name: Build container image
        uses: docker/build-push-action@v6
        with:
          context: .
          # only single arch on branches, because of
          # ERROR: docker exporter does not currently support exporting manifest lists
          platforms: linux/amd64
          push: false
          load: true
          tags: iplike-builder:b${{ github.run_number }}
      - name: Save image as artifact
        run: docker image save iplike-builder:b${{ github.run_number }} -o build/iplike-builder.oci
      - name: Persist OCI
        uses: actions/upload-artifact@v4
        with:
          name: iplike-builder-oci
          path: build/iplike-builder.oci
